name = "ATM100"
author = "ZakW07"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c719f0761f6d07b1975a9bcbb6f945403a49059033fee6280ac0e2cdc2ff646b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
