name = "ATM100"
author = "ZakW07"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ffd17fb8c8fc9d6488e0e81aec3840a528809fec8109d457167d78d8dbc7a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
