#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 03 22:27:04 BST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
